apps/orders/api/urls.py
from django.urls import path, include

from .views import OrderList, OrderUpdateDestroyView, OrderDetailView

urlpatterns = [
    # Orders
    path('orders/', OrderList.as_view(), name=OrderList.name),
    path('orders/<int:pk>/', OrderUpdateDestroyView.as_view(), name=OrderUpdateDestroyView.name),
    path('orders/<int:pk>/detail/', OrderDetailView.as_view(), name=OrderDetailView.name),
]

apps/orders/urls.py
from django.urls import path

from .views import *

app_name = "orders"

urlpatterns = [
    # Order
    path('orders/', OrderListView.as_view(), name=OrderListView.name),
    path('others/', OtherListView.as_view(), name=OtherListView.name),
    path('orders/create/', CreateAndUpdateOrderView.as_view(), name='order_create'),
    path('orders/<int:pk>/update/', CreateAndUpdateOrderView.as_view(), name='order_update'),
	path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),

    # Order Detail
    path('orders/<int:order_id>/detail/', CreateOrderDetailView.as_view(), name='order_detail_create'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False), name='home'),

    # APPS
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.products.urls', namespace='products')),
    path('', include('apps.customers.urls', namespace='customers')),
    path('', include('apps.orders.urls', namespace='orders')),

    # Backend API
    path('api/<str:version>/', include('apps.accounts.api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orders/models.py
import datetime
from decimal import Decimal

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.db.models import Sum
from django.urls import reverse

from apps.commons.models import AuditBaseAbstract
from apps.products.models import Product
from apps.customers.models import Customer


class Order(AuditBaseAbstract):
    """Model for order fields"""

    title = models.CharField(max_length=150, verbose_name=_('title'),
        help_text=_('Descriptive order title'),)
    value = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    discount = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    final_value = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    is_paid = models.BooleanField(default=True)
    customer = models.ForeignKey(Customer,
        on_delete=models.CASCADE,
        related_name='customers'
    )
    class Meta:
        """Meta data respresentation"""
        db_table = "order"
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        order_items = self.order_items.all()
        self.value = order_items.aggregate(Sum('total_price'))['total_price__sum'] if order_items.exists() else 0.00
        self.final_value = Decimal(self.value) - Decimal(self.discount)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title if self.title else 'New Order'

    def get_edit_url(self):
        return reverse('update_order', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('delete_order', kwargs={'pk': self.id})

    @property
    def get_products(self):
        products = self.order_items\
            .select_related(
                "product",
            )
        return products


class OrderDetail(models.Model):
    """Model for order detail fields"""

    product = models.ForeignKey(Product,
        on_delete=models.PROTECT,
        related_name='product_items'
    )
    order = models.ForeignKey(Order,
        on_delete=models.CASCADE,
        related_name='order_items'
    )
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    discount_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    final_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)
    total_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=20)

    class Meta:
        """Meta data respresentation"""
        db_table = "orderdetail"

    def save(self,  *args, **kwargs):
        self.final_price = self.discount_price if self.discount_price > 0 else self.price
        self.total_price = Decimal(self.quantity) * Decimal(self.final_price)
        super().save(*args, **kwargs)
        self.order.save()

    def __str__(self):
        return f'{self.order.title} - {self.product.name}'

apps/orders/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from apps.customers.models import Customer
from .models import Order, OrderDetail


class OrderForm(forms.ModelForm):
    """
    Form for Order.
    """
    customer = forms.ModelChoiceField(
        queryset=Customer.objects.all(),
        label=u"Customer",
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control', }
        ),
    )
    class Meta:
        model = Order
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Ex: First order', 'class': 'form-control', }),
        }
        exclude = ['value', 'discount', 'final_value', ]


class OtherForm(forms.ModelForm):
    """
    Form for Order.
    """
    customer = forms.ModelChoiceField(
        queryset=Customer.objects.all(),
        label=u"Customer",
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control', }
        ),
    )
    class Meta:
        model = Order
        fields = '__all__'
        exclude = ['value', 'discount', 'final_value', 'title', 'is_paid', ]


class OrderDetailForm(forms.ModelForm):
    """
    Form for Order Detail.
    """
    class Meta:
        model = OrderDetail
        fields = '__all__'
        exclude = ['order', 'discount_price', 'final_price', 'total_price',  ]

apps/orders/api/views.py
from django.utils.translation import gettext_lazy as _
from rest_framework import status, generics
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import TokenAuthentication

from apps.customers.models import Customer
from .serializers import OrderSerializer, OrderDetailSerializer
from .pagination import OrderPageNumberPagination
from ..models import Order, OrderDetail
from ..forms import OrderDetailForm

class OrderList(generics.ListCreateAPIView):
    """
    Order List View
    """
    serializer_class = OrderSerializer
    queryset = Order.objects.all()
    name = 'Order List'
    permission_classes = [IsAuthenticated,]
    authentication_class = (TokenAuthentication,)
    pagination_class = OrderPageNumberPagination

    def get_queryset(self):
        kwargs = {}
        start_date = self.request.GET.get('start_date')
        end_date = self.request.GET.get('end_date')
        customer = self.request.GET.get('customer')
        if customer:
            kwargs['customer_id'] = customer
        if start_date and end_date:
            kwargs['created_at__range'] = (start_date, end_date)
        if start_date:
            kwargs['created_at__gte'] = start_date
        if end_date:
            kwargs['created_at__lte'] = end_date

        return Order.objects.filter(**kwargs)

    def create(self, request, *args, **kwargs):
        customer_id = request.data.get("customer")
        customer = Customer.objects.filter(id=customer_id).first()
        if not customer:
            res = {
                "error": 'The customer {} does not exist.'.format(customer_name),
            }
            return Response(res, status=status.HTTP_401_UNAUTHORIZED)

        if customer.products.count() <= 5:
            serializer = self.get_serializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
        else:
            res = {
                "error": 'The number of available products must be less than 5',
            }
            return Response(res, status=status.HTTP_401_UNAUTHORIZED)



class OrderUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    """
    Order, Update and Destroy View
    """
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    name = 'Order Update and destroy'
    lookup_field = 'pk'
    authentication_classes = (TokenAuthentication,)
    permission_classes = [IsAuthenticated,]


class OrderDetailView(generics.ListCreateAPIView):

    name = 'List and Create Order Detail'
    serializer_class = OrderDetailSerializer
    queryset = OrderDetail.objects.all()

    #authentication_classes = (TokenAuthentication,)
    #permission_classes = [IsAuthenticated, ]

    def create(self, request, *args, **kwargs):
        response = super().create(request, *args, **kwargs)
        return Response({
            'status': status.HTTP_200_OK,
            'message': 'Order detail save successful!',
            'data': response.data
        })

apps/orders/views.py
from django.db.models import Q
from django.db import transaction
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.views.generic import DeleteView, TemplateView

from apps.commons.views import ListViewMixin, CreateAndUpdateViewMixin
from apps.commons.helpers import uw_add_alert

from apps.customers.models import Customer

from .models import Order, OrderDetail
from .forms import OrderForm, OtherForm, OrderDetailForm

@method_decorator(login_required, name='dispatch')
class OtherListView(TemplateView):
    """
    List view for other orders
    """
    name = 'other_list'
    template_name='orders/other_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        other_form = OtherForm()
        context["customers"] = Customer.objects.all()
        context["form"] = other_form
        return context


@method_decorator(login_required, name='dispatch')
class OrderListView(ListViewMixin):
    """
    List view for orders
    """
    name = "order_list"
    model = Order
    paginate_by = 8

    def get_queryset(self, tab=None):
        """
        Queryset giving only the current forms
        """
        keyword = self.request.GET.get('keyword', None)
        queryset = self.model.objects.all().order_by('-id')
        if keyword:
            queryset = self.model.objects.filter(
                Q(title__icontains=keyword) |
                Q(customer__name__icontains=keyword)
            )
        return queryset

    def get_success_url(self):
        return reverse_lazy("orders:order_list")



@method_decorator(login_required, name='dispatch')
class CreateAndUpdateOrderView(CreateAndUpdateViewMixin):
    """
    Create and update order
    """
    model = Order
    form_class = OrderForm

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the form with create or update option
        """
        sid = transaction.savepoint()
        try:
            obj = form.save(commit=False)
            if obj.customer.products.count() <= 5:
                obj.save()
                form.save_m2m()
                msg = _('Order save successful!')
                uw_add_alert(self.request, msg,type_message="success")
            else:
                msg = _('The number of available products must be less than 5')
                uw_add_alert(self.request, msg,type_message="error")
            transaction.savepoint_commit(sid)
            return redirect(self.get_success_url())
        except Exception as e:
            uw_add_alert(self.request, e, "error")
            transaction.savepoint_rollback(sid)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy("orders:order_list")


@method_decorator(login_required, name='dispatch')
class OrderDeleteView(DeleteView):
    """
    Order delete view
    """
    model = Order

    def get_success_url(self):
        return reverse_lazy("orders:order_list")


@method_decorator(login_required, name='dispatch')
class CreateOrderDetailView(CreateAndUpdateViewMixin):
    """
    Create order detail
    """
    model = OrderDetail
    form_class = OrderDetailForm
    order = None

    def dispatch(self, *args, **kwargs):
        order_id = self.kwargs.get("order_id", None)
        self.order = Order.objects.filter(id=order_id).first()
        return super().dispatch(*args, **kwargs)

    def get_form(self, form_class=None):
        """Return an instance of the form to be used in this view."""
        form = super().get_form(form_class)
        products = self.order.customer.products.all()
        form.fields['product'].queryset = products
        return form

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the form with create or update option
        """
        sid = transaction.savepoint()
        try:
            obj = form.save(commit=False)
            obj.order = self.order
            obj.save()
            msg = _('Order detail save successful!')
            uw_add_alert(self.request, msg,type_message="success")
            transaction.savepoint_commit(sid)
            return redirect(self.get_success_url())
        except Exception as e:
            uw_add_alert(self.request, e, "error")
            transaction.savepoint_rollback(sid)
        return super().form_invalid(form)

    def form_invalid(self, form):
        print(form)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy("orders:order_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order"] = self.order
        return context

apps/orders/templates/orders/order_confirm_delete.html
{% load i18n %}

{% if object %}
    {% trans 'delete order'|title as modal_title %}
    {% url 'orders:order_delete' object.id as url_delete %}
{% endif %}

<form action="{{ url_delete }}" method="post">
    {% csrf_token %}
    <p>{% trans '¿Are you sure you want to delete' %} "{{ object }}"?</p>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'close'|title %}</button>
        <button type="submit" class="btn btn-danger" name="{% trans 'delete'|title %}">
            <i class="fas fa-trash-alt mr-2"></i> {{ modal_title }}
        </button>
    </div>
</form>

apps/orders/templates/orders/order_form.html
{% load static %}
{% load i18n %}

{% if object %}
    {% trans 'update order'|title as modal_title %}
    {% url 'orders:order_update' object.id as url_view %}
{% else %}
    {% trans 'add order'|title as modal_title %}
    {% url 'orders:order_create' as url_view %}
{% endif %}

<form action="{{ url_view }}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12">
            <h3 class="text-center text-gray-666">{{ modal_title }}</h3>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 px-5 pt-2 text-gray-666">
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.title.label }}</label>
                        <div class="col-12">
                            {{ form.title }}
                            <div class="text-danger">
                                {{ form.title.errors }}
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.customer.label }}</label>
                        <div class="col-12">
                            {{ form.customer }}
                            <div class="text-danger">
                                {{ form.customer.errors }}
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-12 text-right my-2">
                <button type="button" class="btn btn-secondary text-uppercase mr-3" data-dismiss="modal">
                    {% trans 'cancel'|title %}
                    <i class="fa fa-chevron-left float-left mr-2 mt-1"></i>
                </button>
                <button class="btn btn-save-blue text-uppercase" type="submit"
                    name="{% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}">
                    {% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}
                    <i class="fa fa-save float-left mr-2 mt-1"></i>
                </button>
            </div>

        </div>
    </div>
</form>

apps/orders/templates/orders/order_list.html
{% extends 'orders/orders_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Orders' %}
{% endblock %}

{% block content %}
    {% url 'orders:order_list' as url_list %}

    <div class="container-fluid mb-5">

        <div class="container-fluid border-top-1px-gray" style="margin-top: -1px;">
            {% include 'utils/_messages_list.html' %}
            <div class="row pt-5 pb-4">
                {% include 'utils/_search.html' with url_list=url_list %}
                <div class="col-12 col-sm-6 col-md-6 col-lg-7 pr-0 text-left text-sm-right text-md-right text-lg-right">
                    <a class="btn btn-blue2 text-uppercase" title="{% trans 'add'|title %}" role="button"
                        onclick="CreateAndUpdateOrder('{% url "orders:order_create" %}');"
                        href="javascript:void(0);"
                        data-toggle="modal" data-target=".bd-example-modal-lg">
                        {% trans "add"|title %}
                        <i class="fas fa-plus-circle float-left mr-2 mt-1"></i>
                    </a>
                </div>
                {% include 'orders/utils/_create_order.html' %}
            </div>

            <div class="row bg-white" role="tabpanel">
                <div class="col-lg-12 table-responsive px-0">
                    <table class="table table-hover">
                        <thead>
                            <tr class="font-weight-500 text-gray-666 text-capitalize">
                                <th scope="col" class="align-middle border-top-0 border-left pr-0">{% trans '#' %}</th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'title'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'customer'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'total'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'products'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0 text-center"><div class="border-right">{% trans 'actions'|title %}</div></th>
                            </tr>
                        </thead>
                        <tbody class="font-weight-300">
                        {% for order in object_list %}
                            {% include 'orders/utils/_row_order.html' %}
                        {% empty %}
                            <tr>
                                <td class="text-center" colspan="7">{% trans 'You have no orders yet' %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'utils/_paginator.html' %}
                </div>
            </div>
            {% include 'orders/utils/_delete_order.html' %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        function DeleteOrder(url) {
            $('.modal-body').load(url,function(){
                $('#deleteOrder').modal({show:true});
            });
        }
        function CreateAndUpdateOrder(url) {
            $('.modal-body').load(url,function(){
                $('#createOrder').modal({show:true});
            });
        }
        document.getElementById("year").innerHTML = new Date().getFullYear();
    </script>
{% endblock scripts %}

{% block fixed-bottom %}fixed-bottom{% endblock %}

apps/orders/templates/orders/orderdetail_form.html
{% load static %}
{% load i18n %}

{% trans 'add order detail'|title as modal_title %}
{% url 'orders:order_detail_create' order.id as url_view %}

<form action="{{ url_view }}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12">
            <h3 class="text-center text-gray-666">{{ modal_title }}</h3>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 px-5 pt-2 text-gray-666">
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    {% include 'utils/_form.html' %}

                </div>
            </div>

            <div class="col-12 text-right my-2">
                <button type="button" class="btn btn-secondary text-uppercase mr-3" data-dismiss="modal">
                    {% trans 'cancel'|title %}
                    <i class="fa fa-chevron-left float-left mr-2 mt-1"></i>
                </button>
                <button class="btn btn-save-blue text-uppercase" type="submit"
                    name="{% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}">
                    {% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}
                    <i class="fa fa-save float-left mr-2 mt-1"></i>
                </button>
            </div>

        </div>
    </div>
</form>

apps/orders/templates/orders/orders_base.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'navbar.html' with active='orders'  %}
{% endblock %}

apps/orders/templates/orders/other_list.html
{% extends 'orders/orders_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Orders' %}
{% endblock %}

{% block navbar %}
{% include 'navbar.html' with active='orders by customer'  %}
{% endblock %}

{% block content %}
    {% url 'orders:order_list' as url_list %}

    <div class="container-fluid mb-5">

        <div class="container-fluid border-top-1px-gray" style="margin-top: -1px;">

            <div class="row pt-5 pb-4">
               <div class=" col-12 col-sm-6 col-md-6 col-lg-5 pl-0 search-bar">
                    <form method="get">
                        {{ form.as_p }}
                    </form>
                </div>
            </div>

            <div class="row bg-white" role="tabpanel">
                <div class="col-lg-12 table-responsive px-0">
                    <table class="table table-hover">
                        <thead>
                            <tr class="font-weight-500 text-gray-666 text-capitalize">
                                <th scope="col" class="align-middle border-top-0 border-left pr-0 text-center">{% trans 'Creation Date' %}</th>
                                <th scope="col" class="align-middle border-top-0 border-left pr-0 text-center">{% trans 'Order ID' %}</th>
                                <th scope="col" class="align-middle border-top-0 border-left pr-0 text-center">{% trans 'Total' %}</th>
                                <th scope="col" class="align-middle border-top-0 border-left pr-0 text-center">{% trans 'Title' %}</th>
                                <th scope="col" class="align-middle border-top-0 border-left pr-0 ">{% trans 'Products' %}</th>
                            </tr>
                        </thead>
                        <tbody class="font-weight-300">
                        {% for order in object_list %}
                            {% include 'orders/utils/_row_order.html' %}
                        {% empty %}
                            <tr>
                                <td class="text-center" id="not_orders" colspan="7">{% trans 'You have no orders yet' %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'utils/_paginator.html' %}
                </div>
            </div>
            {% include 'orders/utils/_delete_order.html' %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function() {
            $("#id_customer").change(function() {
                customer_id = $('#id_customer option:selected').val();
                if(customer_id){
                    url = "/api/v1/orders/";
                    $.ajax({
                        method: "GET",
                        url: url,
                        data: {
                            'customer': customer_id,
                        },
                        success: function (data) {
                            results = data.results;
                            if (results.length > 0) {
                                $("tbody").empty();
                                for (let i = 0; i < results.length; i++) {
                                    let products = results[i]['products'].split(',');
                                    product_list = [];
                                    if (products.length > 0) {
                                        for (let j=0; j< products.length; j++){
                                            opt = `<span class="badge badge-pill badge-secondary">${products[j]}</span>`;
                                            product_list.push(opt)
                                        }
                                    }else{
                                        opt = `<span class="badge badge-pill badge-secondary">The customer have no products yet</span>`;
                                        product_list.push(opt)
                                    }
                                    var res = `<tr id="customer-${results[i]['id']}">
                                        <td scope="row" class="align-middle text-gray-666 text-center"> ${results[i]['created_at']} </td>
                                        <td scope="row" class="align-middle text-gray-666 text-center"> ${i+1} </td>
                                        <td scope="row" class="align-middle text-center">
                                            <span class="font-weight-600 text-gray-666 ">
                                                <i class="fas fa-dollar-sign my-2 mr-2 text-blue"></i>
                                                ${results[i]['final_value']}
                                            </span>
                                        </td>
                                        <td scope="row" class="align-middle text-center"> ${results[i]['title']} </td>
                                        <td scope="row" class="align-middle"> ${product_list} </td> </tr>`
                                    $("tbody").append(res);
                                }
                            }else{
                                var res = `<tr > <td scope="row" class="text-center" colspan="7"> ${"The customer have no orders yet"} </td> </tr>`
                                $("tbody").html(res);
                            }
                        }
                    });
                }
            });
        });
        document.getElementById("year").innerHTML = new Date().getFullYear();
    </script>
{% endblock scripts %}

{% block fixed-bottom %}fixed-bottom{% endblock %}