apps/products/api/urls.py
from django.urls import path, include

from .views import ProductList, ProductUpdateDestroyView

urlpatterns = [
    # Products
    path('products/', ProductList.as_view(), name=ProductList.name),
    path('products/<int:pk>/', ProductUpdateDestroyView.as_view(), name=ProductUpdateDestroyView.name),
]

apps/products/urls.py
from django.urls import path

from .views import *

app_name = "products"

urlpatterns = [
    path('products/', ProductListView.as_view(), name=ProductListView.name),
    path('products/create/', CreateAndUpdateProductView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', CreateAndUpdateProductView.as_view(), name='product_update'),
	path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False), name='home'),

    # APPS
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.products.urls', namespace='products')),
    path('', include('apps.customers.urls', namespace='customers')),
    path('', include('apps.orders.urls', namespace='orders')),

    # Backend API
    path('api/<str:version>/', include('apps.accounts.api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.commons.models import AuditBaseAbstract
from .managers import ProductManager


class Product(AuditBaseAbstract):
    """Model for product fields"""

    name = models.CharField(max_length=150, unique=True, verbose_name=_('name'),
        help_text=_('Descriptive product name'),)
    description = models.TextField(verbose_name=_('description'),
        help_text=_('Description product'), blank=True, null=True)
    active = models.BooleanField(default=True)
    price = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    discount_value = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    final_value = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    #quantity = models.PositiveIntegerField(default=0)

    objects = models.Manager()
    broswer = ProductManager()

    class Meta:
        """Meta data respresentation"""
        db_table = "product"
        verbose_name_plural = 'Products'

    def save(self, *args, **kwargs):
        self.final_value = self.discount_value if self.discount_value > 0 else self.price
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

apps/products/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Product

class ProductForm(forms.ModelForm):
    """
    Form for Product.
    """

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Ex: Product test','class': 'form-control', }),
            'description': forms.TextInput(
                attrs={'placeholder': 'Ex: This is a product test', 'autofocus': True, 'class': 'form-control search-round'}
            ),
            'price': forms.NumberInput(attrs={'class': 'form-control', }),
        }
        exclude = ['final_value', 'discount_value', ]

apps/products/api/views.py
from django.utils.translation import gettext_lazy as _
from rest_framework import status, generics
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import TokenAuthentication


from .serializers import ProductSerializer
from .pagination import ProductPageNumberPagination

from ..models import Product


class ProductList(generics.ListCreateAPIView):
    """
    Product List View
    """
    serializer_class = ProductSerializer
    queryset = Product.objects.all()
    name = 'Product List'
    permission_classes = [IsAuthenticated,]
    authentication_class = (TokenAuthentication,)
    pagination_class = ProductPageNumberPagination

    def get_queryset(self):
        name = self.request.GET.get('name')
        active = self.request.GET.get('active')
        kwargs = {}
        if name:
            kwargs['name'] = name
        if active:
            kwargs['active'] = active

        return Product.objects.filter(**kwargs)

    def perform_create(self, serializer):
        serializer.save()


class ProductUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    name = 'Product Update and destroy'
    lookup_field = 'pk'
    authentication_classes = (TokenAuthentication,)
    permission_classes = [IsAuthenticated,]

apps/products/views.py
from django.db import transaction
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.views.generic import DeleteView

from apps.commons.views import ListViewMixin, CreateAndUpdateViewMixin
from apps.commons.helpers import uw_add_alert

from .models import Product
from .forms import ProductForm


@method_decorator(login_required, name='dispatch')
class ProductListView(ListViewMixin):
    """
    List view for fields
    """
    name = "product_list"
    model = Product
    paginate_by = 8

    def get_success_url(self):
        return reverse_lazy("products:product_list")



@method_decorator(login_required, name='dispatch')
class CreateAndUpdateProductView(CreateAndUpdateViewMixin):
    """
    Create or update a product
    """
    model = Product
    form_class = ProductForm

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the form with create or update option
        """
        sid = transaction.savepoint()
        try:
            obj = form.save(commit=False)
            obj.save()
            msg = _('Product save successful!')
            uw_add_alert(self.request, msg,type_message="success")
            transaction.savepoint_commit(sid)
            return redirect(self.get_success_url())
        except Exception as e:
            uw_add_alert(self.request, e, "error")
            transaction.savepoint_rollback(sid)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy("products:product_list")


@method_decorator(login_required, name='dispatch')
class ProductDeleteView(DeleteView):
    """
    Product delete view
    """
    model = Product

    def get_success_url(self):
        return reverse_lazy("products:product_list")

apps/products/templates/products/product_confirm_delete.html
{% load i18n %}

{% if object %}
    {% trans 'delete product'|title as modal_title %}
    {% url 'products:product_delete' object.id as url_delete %}
{% endif %}

<form action="{{ url_delete }}" method="post">
    {% csrf_token %}
    <p>{% trans '¿Are you sure you want to delete' %} "{{ object }}"?</p>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'close'|title %}</button>
        <button type="submit" class="btn btn-danger" name="{% trans 'delete'|title %}">
            <i class="fas fa-trash-alt mr-2"></i> {{ modal_title }}
        </button>
    </div>
</form>

apps/products/templates/products/product_form.html
{% load static %}
{% load i18n %}

{% if object %}
    {% trans 'update product'|title as modal_title %}
    {% url 'products:product_update' object.id as url_view %}
{% else %}
    {% trans 'add product'|title as modal_title %}
    {% url 'products:product_create' as url_view %}
{% endif %}

<form action="{{ url_view }}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12">
            <h3 class="text-center text-gray-666">{{ modal_title }}</h3>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 px-5 pt-2 text-gray-666">
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.name.label }}</label>
                        <div class="col-12">
                            {{ form.name }}
                            <div class="text-danger">
                                {{ form.name.errors }}
                            </div>
                            <small id="descriptionHelpBlock" class="form-text text-muted">
                                {{ form.name.help_text }}
                            </small>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.description.label }}</label>
                        <div class="col-12">
                            {{ form.description }}
                            <div class="text-danger">
                                {{ form.description.errors }}
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.price.label }}</label>
                        <div class="col-12">
                            {{ form.price }}
                            <div class="text-danger">
                                {{ form.price.errors }}
                            </div>
                            <small id="descriptionHelpBlock" class="form-text text-muted">
                                {{ form.price.help_text }}
                            </small>
                        </div>
                    </div>

                    {% if object %}
                    <div class="form-row mt-4">
                        <div class="form-group col-md-12">
                            {{ form.active.label_tag }}
                            {{ form.active }}
                            <div class="text-danger">
                                {{ form.active.errors }}
                            </div>
                            <small id="stateHelpBlock" class="form-text text-muted">
                                {{ form.active.help_text }}
                            </small>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>

            <div class="col-12 text-right my-2">
                <button type="button" class="btn btn-secondary text-uppercase mr-3" data-dismiss="modal">
                    {% trans 'cancel'|title %}
                    <i class="fa fa-chevron-left float-left mr-2 mt-1"></i>
                </button>
                <button class="btn btn-save-blue text-uppercase" type="submit"
                    name="{% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}">
                    {% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}
                    <i class="fa fa-save float-left mr-2 mt-1"></i>
                </button>
            </div>

        </div>
    </div>
</form>

apps/products/templates/products/product_list.html
{% extends 'products/products_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Products' %}
{% endblock %}

{% block content %}
    {% url 'products:product_list' as url_list %}

    <div class="container-fluid mb-5">

        <div class="container-fluid border-top-1px-gray" style="margin-top: -1px;">
            {% include 'utils/_messages_list.html' %}
            <div class="row pt-5 pb-4">
                {% include 'utils/_search.html' with url_list=url_list %}
                <div class="col-12 col-sm-6 col-md-6 col-lg-7 pr-0 text-left text-sm-right text-md-right text-lg-right">
                    <a class="btn btn-blue2 text-uppercase" title="{% trans 'add'|title %}" role="button"
                        onclick="CreateAndUpdateProduct('{% url "products:product_create" %}');"
                        href="javascript:void(0);"
                        data-toggle="modal" data-target=".bd-example-modal-lg">
                        {% trans "add"|title %}
                        <i class="fas fa-plus-circle float-left mr-2 mt-1"></i>
                    </a>
                </div>
                {% include 'products/utils/_create_product.html' %}
            </div>

            <div class="row bg-white" role="tabpanel">
                <div class="col-lg-12 table-responsive px-0">
                    <table class="table table-hover">
                        <thead>
                            <tr class="font-weight-500 text-gray-666 text-capitalize">
                                <th scope="col" class="align-middle border-top-0 border-left pr-0">{% trans '#' %}</th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'name'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'description'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'status'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'price'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0 text-center"><div class="border-right">{% trans 'actions'|title %}</div></th>
                            </tr>
                        </thead>
                        <tbody class="font-weight-300">
                        {% for product in object_list %}
                            {% include 'products/utils/_row_product.html' %}
                        {% empty %}
                            <tr>
                                <td class="text-center" colspan="7">{% trans 'You have no products yet' %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'utils/_paginator.html' %}
                </div>
            </div>
            {% include 'products/utils/_delete_product.html' %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        function DeleteProduct(url) {
            $('.modal-body').load(url,function(){
                $('#deleteProduct').modal({show:true});
            });
        }
        function CreateAndUpdateProduct(url) {
            $('.modal-body').load(url,function(){
                $('#createProduct').modal({show:true});
            });
        }
        document.getElementById("year").innerHTML = new Date().getFullYear();
    </script>
{% endblock scripts %}

{% block fixed-bottom %}fixed-bottom{% endblock %}

apps/products/templates/products/products_base.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'navbar.html' with active='products'  %}
{% endblock %}