apps/customers/api/urls.py
from django.urls import path, include

from .views import CustomerList, CustomerUpdateDestroyView

urlpatterns = [
    # Customers
    path('customers/', CustomerList.as_view(), name=CustomerList.name),
    path('customers/<int:pk>/', CustomerUpdateDestroyView.as_view(), name=CustomerUpdateDestroyView.name),
]

apps/customers/urls.py
from django.urls import path

from .views import *

app_name = "customers"

urlpatterns = [
    path('customers/', CustomerListView.as_view(), name=CustomerListView.name),
    path('customers/create/', CreateAndUpdateCustomerView.as_view(), name='customer_create'),
    path('customers/<int:pk>/update/', CreateAndUpdateCustomerView.as_view(), name='customer_update'),
	path('customers/<int:pk>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False), name='home'),

    # APPS
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.products.urls', namespace='products')),
    path('', include('apps.customers.urls', namespace='customers')),
    path('', include('apps.orders.urls', namespace='orders')),

    # Backend API
    path('api/<str:version>/', include('apps.accounts.api.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/customers/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import PersonAbstract
from apps.products.models import Product


class Customer(PersonAbstract):
    """Model for customer fields"""

    name = models.CharField(max_length=191, verbose_name=_('name'),
        help_text=_('customer name'),)
    email = models.EmailField(unique=True, error_messages={'unique': _("A customer with this email already exists."), },
        verbose_name=_('Email address'),
        help_text=_('The email address is the same username.'))

    products = models.ManyToManyField(Product, blank=True,
        verbose_name=_('available products'),
        help_text=_('available products by customer')
    )

    class Meta:
        """Meta data respresentation"""
        db_table = "customer"

    def __str__(self):
        return self.name

apps/customers/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from apps.products.models import Product
from .models import Customer


class CustomerForm(forms.ModelForm):
    """
    Form for Customer.
    """
    products = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(),
        label=u"Available Products",
        required=False,
        widget=forms.CheckboxSelectMultiple(),
    )
    class Meta:
        model = Customer
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Ex: Jhon Doe', 'class': 'form-control', }),
            'email': forms.EmailInput(attrs={'placeholder': 'Ex: jhon.doe@gmail.com', 'class': 'form-control', }),
        }
        exclude = ['final_value', 'discount_value', ]

apps/customers/api/views.py
from django.utils.translation import gettext_lazy as _
from rest_framework import status, generics
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import TokenAuthentication


from .serializers import CustomerSerializer
#from .permissions import IsOwnerOrReadOnly
from .pagination import CustomerPageNumberPagination

from ..models import Customer


class CustomerList(generics.ListCreateAPIView):
    """
    Customer List View
    """
    serializer_class = CustomerSerializer
    queryset = Customer.objects.all()
    name = 'Customer List'
    permission_classes = [IsAuthenticated,]
    authentication_class = (TokenAuthentication,)
    pagination_class = CustomerPageNumberPagination

    def get_queryset(self):
        name = self.request.GET.get('name')
        email = self.request.GET.get('email')
        kwargs = {}
        if name:
            kwargs['name'] = name
        if email:
            kwargs['email'] = email

        return Customer.objects.filter(**kwargs)

    def perform_create(self, serializer):
        serializer.save()


class CustomerUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer
    name = 'Customer Update and destroy'
    lookup_field = 'pk'
    authentication_classes = (TokenAuthentication,)
    permission_classes = [IsAuthenticated,]

apps/customers/views.py
from django.db import transaction
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.views.generic import DeleteView

from apps.commons.views import ListViewMixin, CreateAndUpdateViewMixin
from apps.commons.helpers import uw_add_alert

from .models import Customer
from .forms import CustomerForm


@method_decorator(login_required, name='dispatch')
class CustomerListView(ListViewMixin):
    """
    List view for fields
    """
    name = "customer_list"
    model = Customer
    paginate_by = 8

    def get_success_url(self):
        return reverse_lazy("customers:customer_list")



@method_decorator(login_required, name='dispatch')
class CreateAndUpdateCustomerView(CreateAndUpdateViewMixin):
    """
    Create and update customer
    """
    model = Customer
    form_class = CustomerForm

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the form with create or update option
        """
        sid = transaction.savepoint()
        try:
            obj = form.save(commit=False)
            obj.save()
            form.save_m2m()
            msg = _('Customer save successful!')
            uw_add_alert(self.request, msg,type_message="success")
            transaction.savepoint_commit(sid)
            return redirect(self.get_success_url())
        except Exception as e:
            uw_add_alert(self.request, e, "error")
            transaction.savepoint_rollback(sid)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy("customers:customer_list")


@method_decorator(login_required, name='dispatch')
class CustomerDeleteView(DeleteView):
    """
    Customer delete view
    """
    model = Customer

    def get_success_url(self):
        return reverse_lazy("customers:customer_list")

apps/customers/templates/customers/customer_confirm_delete.html
{% load i18n %}

{% if object %}
    {% trans 'delete customer'|title as modal_title %}
    {% url 'customers:customer_delete' object.id as url_delete %}
{% endif %}

<form action="{{ url_delete }}" method="post">
    {% csrf_token %}
    <p>{% trans '¿Are you sure you want to delete' %} "{{ object }}"?</p>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'close'|title %}</button>
        <button type="submit" class="btn btn-danger" name="{% trans 'delete'|title %}">
            <i class="fas fa-trash-alt mr-2"></i> {{ modal_title }}
        </button>
    </div>
</form>

apps/customers/templates/customers/customer_form.html
{% load static %}
{% load i18n %}

{% if object %}
    {% trans 'update customer'|title as modal_title %}
    {% url 'customers:customer_update' object.id as url_view %}
{% else %}
    {% trans 'add customer'|title as modal_title %}
    {% url 'customers:customer_create' as url_view %}
{% endif %}

<form action="{{ url_view }}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-12">
            <h3 class="text-center text-gray-666">{{ modal_title }}</h3>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 px-5 pt-2 text-gray-666">
            <div class="card shadow-sm mb-4">
                <div class="card-body">
                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.name.label }}</label>
                        <div class="col-12">
                            {{ form.name }}
                            <div class="text-danger">
                                {{ form.name.errors }}
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="text-gray-666 font-weight-bold col-12">{{ form.email.label }}</label>
                        <div class="col-12">
                            {{ form.email }}
                            <div class="text-danger">
                                {{ form.email.errors }}
                            </div>
                        </div>
                    </div>
                    {% if object %}
                    <div class="form-group">
                        <label class="text-gray-666 font-weight-bold" for="id_company_type">{{ form.products.label }}:</label>
                        <div class="row mx-0">
                            {% for field in form.products %}
                                {{ field.choice_value }}
                                <div class="col-6 company_type font-size-12 ">
                                    <label for="{{ field.id_for_label }}">
                                        <input type="checkbox" name="{{ field.data.name }}" id="{{ field.id_for_label }}"
                                            value="{{ field.data.value }}" {% if field.data.selected %} checked{% endif %}
                                        >
                                        {{ field.data.label }}
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="text-danger">
                            {{ form.products.errors }}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>

            <div class="col-12 text-right my-2">
                <button type="button" class="btn btn-secondary text-uppercase mr-3" data-dismiss="modal">
                    {% trans 'cancel'|title %}
                    <i class="fa fa-chevron-left float-left mr-2 mt-1"></i>
                </button>
                <button class="btn btn-save-blue text-uppercase" type="submit"
                    name="{% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}">
                    {% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}
                    <i class="fa fa-save float-left mr-2 mt-1"></i>
                </button>
            </div>

        </div>
    </div>
</form>

apps/customers/templates/customers/customer_list.html
{% extends 'customers/customers_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Customers' %}
{% endblock %}

{% block content %}
    {% url 'customers:customer_list' as url_list %}

    <div class="container-fluid mb-5">

        <div class="container-fluid border-top-1px-gray" style="margin-top: -1px;">
            {% include 'utils/_messages_list.html' %}
            <div class="row pt-5 pb-4">
                {% include 'utils/_search.html' with url_list=url_list %}
                <div class="col-12 col-sm-6 col-md-6 col-lg-7 pr-0 text-left text-sm-right text-md-right text-lg-right">
                    <a class="btn btn-blue2 text-uppercase" title="{% trans 'add'|title %}" role="button"
                        onclick="CreateAndUpdateCustomer('{% url "customers:customer_create" %}');"
                        href="javascript:void(0);"
                        data-toggle="modal" data-target=".bd-example-modal-lg">
                        {% trans "add"|title %}
                        <i class="fas fa-plus-circle float-left mr-2 mt-1"></i>
                    </a>
                </div>
                {% include 'customers/utils/_create_customer.html' %}
            </div>

            <div class="row bg-white" role="tabpanel">
                <div class="col-lg-12 table-responsive px-0">
                    <table class="table table-hover">
                        <thead>
                            <tr class="font-weight-500 text-gray-666 text-capitalize">
                                <th scope="col" class="align-middle border-top-0 border-left pr-0">{% trans '#' %}</th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'name'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0"><div class="border-right">{% trans 'email'|title %}</div></th>
                                <th scope="col" class="align-middle border-top-0 pr-0 text-center"><div class="border-right">{% trans 'actions'|title %}</div></th>
                            </tr>
                        </thead>
                        <tbody class="font-weight-300">
                        {% for customer in object_list %}
                            {% include 'customers/utils/_row_customer.html' %}
                        {% empty %}
                            <tr>
                                <td class="text-center" colspan="7">{% trans 'You have no customers yet' %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'utils/_paginator.html' %}
                </div>
            </div>
            {% include 'customers/utils/_delete_customer.html' %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        function DeleteCustomer(url) {
            $('.modal-body').load(url,function(){
                $('#deleteCustomer').modal({show:true});
            });
        }
        function CreateAndUpdateCustomer(url) {
            $('.modal-body').load(url,function(){
                $('#createCustomer').modal({show:true});
            });
        }
        document.getElementById("year").innerHTML = new Date().getFullYear();
    </script>
{% endblock scripts %}

{% block fixed-bottom %}fixed-bottom{% endblock %}

apps/customers/templates/customers/customers_base.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'navbar.html' with active='customers'  %}
{% endblock %}